import type { Metadata } from "next";
import localfont from "next/font/local";
import "./globals.css";
import Providers from "@/components/Providers";
import SideBar from "@/components/SideBar";

const apple = localfont({
  src: [
    {
      path: "../public/fonts/AppleSDGothicNeoH.ttf",
      weight: "900",
    },
    {
      path: "../public/fonts/AppleSDGothicNeoEB.ttf",
      weight: "800",
    },
    {
      path: "../public/fonts/AppleSDGothicNeoB.ttf",
      weight: "700",
    },
    {
      path: "../public/fonts/AppleSDGothicNeoSB.ttf",
      weight: "600",
    },
    {
      path: "../public/fonts/AppleSDGothicNeoM.ttf",
      weight: "500",
    },
    {
      path: "../public/fonts/AppleSDGothicNeoR.ttf",
      weight: "400",
    },
    {
      path: "../public/fonts/AppleSDGothicNeoL.ttf",
      weight: "300",
    },
    {
      path: "../public/fonts/AppleSDGothicNeoT.ttf",
      weight: "200",
    },
    {
      path: "../public/fonts/AppleSDGothicNeoUL.ttf",
      weight: "100",
    },
  ],
  variable: "--font-apple",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={apple.variable}>
        <Providers>
          <main className="w-[1920px] max-h-screen font-apple">
            <SideBar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
